### ISSUE TITLE
Done page - Restart doesn't

### ISSUE THREAD

**Issue by keen-way-software** [ishizuki-tech/SurveyNav2025#2]
Pressing Restart takes the user to the Start page, but the survey can't start.

**Comment by ishizuki-tech** [comment]
Fixed in v0.0.1-20251210-0019

**Comment by keen-way-software** [comment]
Just ran through 6 questions and uploaded in [v0.0.1-20251210-0019](https://github.com/ishizuki-tech/SurveyNav2025/releases/download/v0.0.1-20251210-0019/app-release.apk) - Restart button still fails.

**Comment by ishizuki-tech** [comment]
Fixed by adding Unique ID for ViewModels.
